INSERT INTO boxedtest.cellBlock (cellBlockId) VALUES ('A');
INSERT INTO boxedtest.cellBlock (cellBlockId) VALUES ('B');
INSERT INTO boxedtest.cellBlock (cellBlockId) VALUES ('C');
INSERT INTO boxedtest.cell (cellNr, isolationCell, size, cellBlock) VALUES ('A1',0,'1','A');
INSERT INTO boxedtest.cell (cellNr, isolationCell, size, cellBlock) VALUES ('A2',1,'1','A');
INSERT INTO boxedtest.cell (cellNr, isolationCell, size, cellBlock) VALUES ('A3',1,'1','A');
INSERT INTO boxedtest.cell (cellNr, isolationCell, size, cellBlock) VALUES ('B1',0,'1','B');
INSERT INTO boxedtest.cell (cellNr, isolationCell, size, cellBlock) VALUES ('B2',1,'1','B');
INSERT INTO boxedtest.cell (cellNr, isolationCell, size, cellBlock) VALUES ('B3',1,'1','B');
INSERT INTO boxedtest.crime (name, punishment) VALUES ('Moord', 3650);
INSERT INTO boxedtest.crime (name, punishment) VALUES ('Diefstal', 200);
INSERT INTO boxedtest.crime (name, punishment) VALUES ('Gevecht', 14);
INSERT INTO boxedtest.guard (name) VALUES ('Bob');
INSERT INTO boxedtest.guard (name) VALUES ('Bob');
INSERT INTO boxedtest.guard (name) VALUES ('Bob');
INSERT INTO boxedtest.job (name, duration) VALUES ('Wasserette', 365);
INSERT INTO boxedtest.job (name, duration) VALUES ('WcKuisen', 14);
INSERT INTO boxedtest.job (name, duration) VALUES ('Zagen', 60);
INSERT INTO boxedtest.prisoner (name, isolated, releaseDate) VALUES ('Gert', 0, 50);
INSERT INTO boxedtest.prisoner (name, isolated, releaseDate) VALUES ('Gert', 0, 100);
INSERT INTO boxedtest.prisoner (name, isolated, releaseDate) VALUES ('Gert', 0, 200);
INSERT INTO boxedtest.day (dayNr) VALUES (0);
INSERT INTO boxedtest.day (dayNr) VALUES (0);
INSERT INTO boxedtest.day (dayNr) VALUES (0);
INSERT INTO boxedtest.day (dayNr) VALUES (0);
INSERT INTO boxedtest.day (dayNr) VALUES (0);
